### ISSUE TITLE
behavior of setRange is strange

### ISSUE THREAD

**Issue by iFwu** [aesy/Easy-Bits#2]
In the source code, I don't see the "setRange" method uses the original value to do some calculation.
Maybe it's a bug or I missed the point?

```javascript
it('should set bits to a specific value within a specific range', () => {
	const bitField = new BitField();
	bitField.setRange(3, 1, 4);
	bitField.setRange(0, 1, 4);
	expect(bitField.valueOf()).to.equal(0b0); // expect 0, actually got 8

	bitField.setRange(0, 0, 3);
	expect(bitField.valueOf()).to.equal(0b1000);
});

```

**Comment by aesy** [comment]
Hey there!

There are some issues with your test:
```js
bitField.setRange(3, 1, 4);
``` 
`3` is invalid as an argument for value - it should be one of `0|1|false|true`, although it still works the way you expect.

```js
expect(bitField.valueOf()).to.equal(0b1000);
```
The expected value here is `0b0`, not `0b1000`, since you're reusing the same bitfield that was set to zero just before.

However, this assertion is correct:
```js
expect(bitField.valueOf()).to.equal(0b0); // expect 0, actually got 8
```

... but I can't actually reproduce it. The following test passes:
```js
it('should set bits to a specific value within a specific range', () => {
        const bitField = new BitField();
        bitField.setRange(1, 1, 4);
        expect(bitField.valueOf()).to.equal(0b1110);
        bitField.setRange(0, 1, 4);
        expect(bitField.valueOf()).to.equal(0b0);
});
```

and so does this:
```js
it('should set bits to a specific value within a specific range', () => {
        const bitField = new BitField();
        bitField.setRange(1, 1, 4);
        expect(bitField.valueOf()).to.equal(0b1110);
        bitField.setRange(0, 0, 3);
        expect(bitField.valueOf()).to.equal(0b1000);
});
```

Could you please run these two tests exactly as written and let me know the full output?

**Comment by iFwu** [comment]
> Hey there!
> 
> There are some issues with your test:
> 
> ```js
> bitField.setRange(3, 1, 4);
> ```
> 
> `3` is invalid as an argument for value - it should be one of `0|1|false|true`, although it still works the way you expect.
> 
> ```js
> expect(bitField.valueOf()).to.equal(0b1000);
> ```
> 
> The expected value here is `0b0`, not `0b1000`, since you're reusing the same bitfield that was set to zero just before.
> 
> However, this assertion is correct:
> 
> ```js
> expect(bitField.valueOf()).to.equal(0b0); // expect 0, actually got 8
> ```
> 
> ... but I can't actually reproduce it. The following test passes:
> 
> ```js
> it('should set bits to a specific value within a specific range', () => {
>         const bitField = new BitField();
>         bitField.setRange(1, 1, 4);
>         expect(bitField.valueOf()).to.equal(0b1110);
>         bitField.setRange(0, 1, 4);
>         expect(bitField.valueOf()).to.equal(0b0);
> });
> ```
> 
> and so does this:
> 
> ```js
> it('should set bits to a specific value within a specific range', () => {
>         const bitField = new BitField();
>         bitField.setRange(1, 1, 4);
>         expect(bitField.valueOf()).to.equal(0b1110);
>         bitField.setRange(0, 0, 3);
>         expect(bitField.valueOf()).to.equal(0b1000);
> });
> ```
> 
> Could you please run these two tests exactly as written and let me know the full output?

Thanks for taking a look at it.
The comment placed in the wrong line. It should be place after the last expect sentence:
`expect(bitField.valueOf()).to.equal(0b1000); // expect 8, actually got 0`

But that's not the point. I mistook the "setRange" method usage which is to set all bits of given range to either 0 or 1.
